### ISSUE TITLE
Manually merge pull requests from Anatid/XML-Documentation-for-the-KSP-API

### ISSUE THREAD

**Issue by jrossignol** [KSP-API-docs/XML-Documentation-for-the-KSP-API#1]
The following pull requests should be investigated and manually merged into this repository if appropriate:
- [ ] https://github.com/Anatid/XML-Documentation-for-the-KSP-API/pull/12
- [ ] https://github.com/Anatid/XML-Documentation-for-the-KSP-API/pull/13
- [ ] https://github.com/Anatid/XML-Documentation-for-the-KSP-API/pull/20
- [ ] https://github.com/Anatid/XML-Documentation-for-the-KSP-API/pull/21

**Comment by tomforwood** [comment]
I have reviewed and incorporated most of the changes
